### ISSUE TITLE
Add Provider => sflix.se

### ISSUE THREAD

**Issue by bachig26** [LagradOst/CloudStream-3#1370] opened 2022-07-30 18:00 UTC

**Comment by Blatzar** [comment] 2022-07-30 19:15
Duplicate of sflix.to, use the clone site feature if you want it in the app.

**Closed by Blatzar** 2022-07-30 19:15 UTC

**Comment by bachig26** [comment] 2022-07-31 10:15
> Duplicate of sflix.to, use the clone site feature if you want it in the app.

I tried using clone feature but it (site) doesn't show, is there any example or how to? available for this?
