### ISSUE TITLE
No Links Found / Error 2004

### ISSUE THREAD

**Issue by BlackRabbit22** [LagradOst/CloudStream-3#1031] opened 2022-05-05 08:21 UTC
### Steps to reproduce

Run the application on an android 11 device.

### Expected behavior

Links are found.

### Actual behavior

Playing a stream causes "No links found" pop up.

This issue does not happen with 2.8.16 however it happens with 2.9.24.
The application was tested on three devices, two which are running android 11, and one running android 7. 
2.9.24 works fine on android 7, however the issue occurs on android 11.

I also tested this with and without a VPN and the issue is the same on android 11.

### Cloudstream version

2.9.24

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to pre-release version **[Latest](https://github.com/LagradOst/CloudStream-3/releases)**.
- [X] If related to a provider, I have checked the site and it works, but not the app.
- [X] I will fill out all of the requested information in this form.

**Comment by LagradOst** [comment] 2022-05-05 08:52
What provider? Every single one?

**Comment by BlackRabbit22** [comment] 2022-05-05 10:04
> What provider? Every single one?

@LagradOst 

The following providers:
- 2Embed
- ApiMDB
- Bflix
- Fmovies
- Sflix pro


(They work in my browser).

**Comment by tomeczeka** [comment] 2022-05-05 17:10
same thing happens to me with most providers, also Android 11. rolled back and it's fine now

**Comment by LagradOst** [comment] 2022-05-05 17:19
> same thing happens to me with most providers, also Android 11. rolled back and it's fine now

rolled back android ver or app ver?

**Comment by tomeczeka** [comment] 2022-05-05 17:24
> 

app. i'm on 2.8.16 now and all providers work flawlessly

**Comment by LagradOst** [comment] 2022-05-07 11:30
@BlackRabbit22 try latest preview version and send entire logcat

**Comment by xololunatic** [comment] 2022-05-07 15:40
I don't think it's fixed. I tried 2embed but it's again showing No links Found. But you may have have fixed #1032 becoz i just tried the Asianemebd.io (Asianload) and it's streamsb source and others too is running smoothly

**Comment by JimZiii** [comment] 2022-05-08 01:57
It's not fixed. I had already deleted most of my pre-release files but the providers were still working on 2.9.16
I can't remember exactly when it stopped working but a few days ago at least.
Initially i only noticed it on one provider so i didn't think it was related to the pre-release update i got right before it happened.

**Comment by JimZiii** [comment] 2022-05-08 10:31
Still not working in 2.9.25. Checked the pre-release updates i had on my nvidia shield, and the issue started in **2.9.23**.
Every version before that works just fine.

**Comment by LagradOst** [comment] 2022-05-08 12:37
@Blatzar 2.9.22 was before nicehttp, 2.9.23 was after nicehttp

**Comment by JimZiii** [comment] 2022-05-14 14:57
@LagradOst got an update said to fix nicehttp but it's still not working on my end

**Comment by Blatzar** [comment] 2022-05-14 14:59
That's meant for MAL issues caused by nicehttp
@JimZiii which sites dont work for you?

**Comment by xololunatic** [comment] 2022-05-14 15:04
I checked and these sites are showing "No links Found": but working fine in browsers.

•2emebed

•ApiMDB

•Asiaflix

**Comment by JimZiii** [comment] 2022-05-14 15:14
Oh ok, thought it was meant for this issue since nicehttp was mentioned in here.
It's the same sites as mentioned earlier in this post
2Embed
ApiMDB
Bflix
Fmovies
Sflix pro

**Comment by Blatzar** [comment] 2022-05-14 15:26
Ah this is probably not nicehttp issues, you probably have a shitty isp or alike which blocks the sites. Try VPN.

2Embed: Doesn't work, most probably simply outdated
ApiMDB: Works (try shawshank redemption)
Bflix: Works (try halo)
Fmovies: Works (try halo)
Sflix pro: Works (try halo)

**Comment by JimZiii** [comment] 2022-05-14 15:29
Halo the tv series doesnt work on my end on those sites, i get "no links found"

**Comment by Blatzar** [comment] 2022-05-14 15:35
Try VPN while using the latest pre-release and report results

**Comment by JimZiii** [comment] 2022-05-14 16:20
@Blatzar i tried a vpn and it seems like this issue is only happening in european countries.

If you wanna try a vpn yourself and you open cloudstream right after switching country, try playing a video then closing the app and opening it again for the new ip to register correctly.
I did this on all countries i tried, i even closed the app and reopened it several times after that on each country to get the most reliable results possible.
On every EU country i tried, except for France and UK, i got "no links found" and i tried around 10 EU countries. France, UK and the rest of the world worked just fine.
I tried a few asian countries, a few south american countries and some north american.

Not really sure why it's only in europe, but even in these european countries with vpn or in my own without vpn, we only get this issue in the cloudstream app, the websites all work if i try them ina regular browser.

And it's only on those 5 websites in the app

**Comment by Blatzar** [comment] 2022-05-14 16:25
It works fine in Sweden with and without VPN.
Either way it's not our problem and we cannot fix it beyond what we have already done with DNS settings.

**Comment by JimZiii** [comment] 2022-05-14 18:18
@Blatzar I'm also in Sweden. It's not working at my relatives house with telia as isp, not working on my isp bahnhof or my phone data which is comviq.
Try opening cloudstream on sflix.pro just as an example and try opening Dumbledores secrets, uncharted, turning red.
Without a vpn active. Also, i still have the pre-release files and version 2.9.22 and every single version before it doesn't have this issue, while 2.9.23 and every version after have this issue.

**Comment by JimZiii** [comment] 2022-05-14 18:44
@Blatzar just talked to my brother and it works fine at his house on his phone, so you're probably right, is something on my end.
Do you have any idea how i can fix this problem on my phones and my nvidia shield?
I've tried it on both telia and bahnhof isp's and the data on my phone which is comviq.
Is it some setting on my phone and shield?

**Comment by Blatzar** [comment] 2022-05-14 18:50
Yeah Bahnhof should never fuck up so I doubt it's that :thinking: 

No VPN, clean install works fine for me so i have literally no idea how to replicate or fix. I suppose try changing DNS in app settings and clearing app cache. Also fetch the pre release from the update two hours ago :shrug:

https://user-images.githubusercontent.com/46196380/168444585-d781a838-59ad-46d2-b5b7-3c7b422a7578.mp4

**Comment by JimZiii** [comment] 2022-05-15 22:25
@Blatzar i think i know what's going on. There's more than one issue going on here, and my vpn stopped working altogether no matter which country, which had me confused at first.
But on bflix, fmovies and sflix.pro I'm able to get the links by reloading the links a bunch of times, sometimes 10 times or more.
I'm just guessing here but i think it's due to slow connection and the timeout for initially loading the links runs out, not really sure what's causing it since if i install 2.9.22 I'm getting all the links right away but mcloud still isn't working, but there it's just skipping to the next working link.
But those 3 sites seem to be using the same links so it makes sense they have the same problems.

Secondly, on those same sites the main link seems to be mcloud on most movies and mcloud refuses to load. I only get mcloud auto, the different resolutions agent showing up. The weird part is that I'm still able to download the movies from mcloud and if i reload the links after the download has started all the different mcloud resolution links shows up. But they still refuse to stream, all mcloud links give this error
```
Remote Error
ERROR_CODE_IO_BAD_HTTP_STATUS (2004)
Source Error
```
I'm not really sure about 2embed and apimdb, those two sites are using the same links as each other btw so they have the same issues.
Some newer movies dont have any links but I'm not sure if that's just them not having the movies or not finding the links. But on the ones that do work i seem to be getting the links right away but some of them refuse to stream and give the same error as i mentioned above for mcloud.

Sorry about the lengthy explanation but i hope it helps.

**Comment by JimZiii** [comment] 2022-05-25 16:58
> @Blatzar like BlackRabbit22 mentioned, all the issues have now been fixed but i just want to mention they're still present in the stable version

**Closed** 2022-05-25 17:41 UTC
Labels: bug
