### ISSUE TITLE
subtitles in downloads are not working

### ISSUE THREAD

**Issue by vanhoxx** [LagradOst/CloudStream-3#306] opened 2021-12-06 18:04 UTC
When I download an episode, subtitles are not showing up. Are subtitles not downloading alongside videos or are there any kind of bug here? It's a big issue for a guy like me though.

**Comment by LagradOst** [comment] 2021-12-06 18:16
Check pre release

**Comment by LagradOst** [comment] 2021-12-06 18:43
Srt and vtt issue due to exoplayer being wacked.

**Comment by vanhoxx** [comment] 2021-12-06 18:56
We gonna get a fix in next release, right? UwU

**Comment by ArjixWasTaken** [comment] 2021-12-06 20:36
> We gonna get a fix in next release, right? UwU

Nope can't do, as lagradost said this is an issue on exoplayer's part.

**Comment by LagradOst** [comment] 2021-12-06 20:59
> > We gonna get a fix in next release, right? UwU
> 
> Nope can't do, as lagradost said this is an issue on exoplayer's part.

We can fix by streaming the first part in to check

**Comment by vanhoxx** [comment] 2021-12-06 21:19
> > > We gonna get a fix in next release, right? UwU
> > 
> > Nope can't do, as lagradost said this is an issue on exoplayer's part.
> 
> We can fix by streaming the first part in to check

Uhmm, what does that mean?

**Comment by LagradOst** [comment] 2021-12-06 22:00
> > > > We gonna get a fix in next release, right? UwU
> > > 
> > > 
> > > Nope can't do, as lagradost said this is an issue on exoplayer's part.
> > 
> > 
> > We can fix by streaming the first part in to check
> 
> Uhmm, what does that mean?
The problem is that exoplayer thinks it is a vtt and not an srt and therefore makes the retarded decision of just giving up. Regular videoplayer like vlc or mpv does not require a filetype to play a video or subtitle file because they check the header of the file. My plan is to check the header on downloaded vtt/srt manually to see what type they are so exoplayer can display them.

**Comment by ArjixWasTaken** [comment] 2021-12-06 22:42
> > > > > We gonna get a fix in next release, right? UwU
> > > > 
> > > > 
> > > > Nope can't do, as lagradost said this is an issue on exoplayer's part.
> > > 
> > > 
> > > We can fix by streaming the first part in to check
> > 
> > 
> > Uhmm, what does that mean?
> 
> The problem is that exoplayer thinks it is a vtt and not an srt and therefore makes the retarded decision of just giving up. Regular videoplayer like vlc or mpv does not require a filetype to play a video or subtitle file because they check the header of the file. My plan is to check the header on downloaded vtt/srt manually to see what type they are so exoplayer can display them.

Oh, so it was because it wants the specific MIME type?
Naruhodo

**Comment by LagradOst** [comment] 2022-02-13 16:15
should be fixed

**Closed by LagradOst** 2022-02-13 16:15 UTC
Labels: bruh
