### ISSUE TITLE
[Bug] Posters don't highlight when selecting an item on Android TV

### ISSUE THREAD

**Issue by steamedham544** [LagradOst/CloudStream-3#1000] opened 2022-04-26 11:05 UTC
Using the latest beta. The only items that are highlighted are the posters in the header carousel. Everything else doesn't highlight so I don't know what I'm selecting.

**Comment by LagradOst** [comment] 2022-04-26 11:28
Duplicate of #996

**Closed** 2022-04-26 11:28 UTC
