### ISSUE TITLE
iDK

### ISSUE THREAD

**Issue by laufeyss** [LagradOst/CloudStream-3#655] opened 2022-02-13 16:00 UTC
hello! just new to the app, is there a plan to add 𝘀𝘂𝗯𝘁𝗶𝘁𝗹𝗲 𝘀𝘆𝗻𝗰 option in player to change the subs timing?

**Comment by LagradOst** [comment] 2022-02-13 16:16
duplicate of #36

**Closed by LagradOst** 2022-02-13 16:16 UTC
