### ISSUE TITLE
Provider Request

### ISSUE THREAD

**Issue by Eyepan** [LagradOst/CloudStream-3#43] opened 2021-08-30 07:22 UTC
Can you please add 
https://www3.fbox.to/

I have been using CloudStream for quite a while now and it has become my favourite streaming app just because of how it all just 
_snap_ works. I will be a happier man if fbox could be added here. It is extremely fast, faster than trailers.to and has a wider movie/series selection. Sure it will be worth your time.

With much love,
Pan

**Comment by ArjixWasTaken** [comment] 2021-08-30 19:38
Duplicate of #24

**Closed by ArjixWasTaken** 2021-08-30 19:38 UTC
